# Generated by Django 3.1 on 2021-01-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
                ('trailer_link', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('raiting', models.IntegerField(default=0)),
            ],
        ),
    ]
